development:
  adapter: postgresql
  database: csc517p2_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: csc517p2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: csc517p2_production
  pool: 5
  timeout: 5000
